version: "3.8"

services:
  backend:
    build: .
    container_name: node-backend
    environment:
      - VIRTUAL_HOST=backend.local.test
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=backend.local.test
      - LETSENCRYPT_EMAIL=muhammadirfan187@outlook.com
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - "${APP_PORT}"
    depends_on:
      - mongodb
    networks:
      - proxy

  mongodb:
    image: mongo
    container_name: mongo-db
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - proxy

  mongo-express:
    image: mongo-express
    container_name: node-mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb # Sesuai dengan nama service "mongodb"
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - VIRTUAL_HOST=mongo.local.test
      - VIRTUAL_PORT=8081
    expose:
      - "8081"
    depends_on:
      - mongodb
    networks:
      - proxy

volumes:
  mongodb_data:

networks:
  proxy:
    external: true
